name: Build Extension
on:
    push:
        branches: [master]
        tags: ["v*"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build extensions
              run: npm run build

            - name: Upload Chrome artifact
              uses: actions/upload-artifact@v4
              with:
                  name: chrome-extension
                  path: dist/webtweaks-chrome.zip

            - name: Upload Firefox artifact
              uses: actions/upload-artifact@v4
              with:
                  name: firefox-extension
                  path: dist/webtweaks-firefox.xpi

            - name: Upload unpacked extensions
              uses: actions/upload-artifact@v4
              with:
                  name: unpacked-extensions
                  path: dist/unpacked/

            - name: Create Release
              id: create_release
              if: startsWith(github.ref, 'refs/tags/v')
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: WebTweaks ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: Upload Release Assets
              if: startsWith(github.ref, 'refs/tags/v')
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: dist/webtweaks-chrome.zip
                  asset_name: webtweaks-chrome.zip
                  asset_content_type: application/zip

            - name: Upload Firefox Release Asset
              if: startsWith(github.ref, 'refs/tags/v')
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: dist/webtweaks-firefox.xpi
                  asset_name: webtweaks-firefox.xpi
                  asset_content_type: application/x-xpinstall
