name: Build Extension

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build extensions
      run: npm run build
      
    - name: Upload Chrome artifact
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension
        path: dist/webtweaks-chrome.zip
        
    - name: Upload Firefox artifact
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: dist/webtweaks-firefox.xpi
        
    - name: Upload unpacked extensions
      uses: actions/upload-artifact@v4
      with:
        name: unpacked-extensions
        path: dist/unpacked/
        
    - name: Release assets
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} \
          dist/webtweaks-chrome.zip \
          dist/webtweaks-firefox.xpi
